### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ka11i0** [Decending/E7020E_lab2#1]
1) Bra.
2) Bra.
3) Det ser bra ut, gillar din layout, tänk bara på att decoupling capacitors ska sitta så nära MCUn som möjligt. Du kan också ändra footprinten för restistorerna till 0805, så får du lite mer plats.
4) De spåren du har dragit över sensorytan kommer inte funka då det ska va en cutout där. Sen vet jag inte om man kan ha vias direkt på en komponent, alltså rakt genom resistor kontakten, men funkar mitt på chippet (enligt "experten" jag konsulterat med). Saknas två kontakter, lättfixade dock. Nu när jag ser hur du har gjort fattar jag äntligen hur man använder "filled zones". :) 
5) Som tidigare nämnt har du ingen cutout för PMWn.
6) 2 Errors.

**Comment by Decending** [comment]
Jag har gjort en ny design nu, kolla gärna över att jag har fixat alla problem du har pekat ut!

**Comment by ka11i0** [comment]
Det ser bra ut!
